version: '3.3'
services:
  db:
    build:
      context: ./db
      labels:
        APP_PROJNAME: ${APP_PROJNAME}
        APP_VERSION: ${APP_VERSION}
        APP_BRANCH: ${APP_BRANCH}
        APP_REVISION: ${APP_REVISION}
        APP_CONTAINER_NAME: ${APP_CONTAINER_NAME}
    image: itcw/${APP_PROJNAME}_db:${APP_VERSION:-latest}
    restart: always
    networks:
      - db-tunnel
    ports:
    - 5433:5432
    environment:
      APP_PROJNAME: ${APP_PROJNAME}
      APP_VERSION: ${APP_VERSION}
      APP_BRANCH: ${APP_BRANCH}
      APP_REVISION: ${APP_REVISION}
      APP_CONTAINER_NAME: ${APP_CONTAINER_NAME}

    volumes:
    - database_data:/var/lib/postgresql/data
  bot:
    build:
      context: ./bot
      labels:
        APP_PROJNAME: ${APP_PROJNAME}
        APP_VERSION: ${APP_VERSION}
        APP_BRANCH: ${APP_BRANCH}
        APP_REVISION: ${APP_REVISION}
        APP_CONTAINER_NAME: ${APP_CONTAINER_NAME}
    image: itcw/${APP_PROJNAME}_bot:${APP_VERSION:-latest}
    networks:
      - db-tunnel
    expose:
    - 5000
    ports:
    - 8000:5000
    depends_on:
      - db
    links:
    - db:newbie_db
    environment:
      APP_PROJNAME: ${APP_PROJNAME}
      APP_VERSION: ${APP_VERSION}
      APP_BRANCH: ${APP_BRANCH}
      APP_REVISION: ${APP_REVISION}
      APP_CONTAINER_NAME: ${APP_CONTAINER_NAME}
    volumes:
    - ${APP_PROJPATH}/bot/.env:/usr/src/app/.env
networks:
  db-tunnel:
volumes:
  database_data:
    driver: local
