version: '3.3'
services:
  db:
    env_file:
      - secrets.env
      - generated.env
    build:
      context: ./db
    image: itcw/${APP_PROJNAME}_db:${APP_VERSION}
    restart: always
    networks:
      db-tunnel:
        aliases:
          - db
    ports:
    - 5433:5432
    volumes:
    - database_data:/var/lib/postgresql/data
  bot:
    env_file:
      - secrets.env
      - generated.env
    build:
      context: ./bot
    image: itcw/${APP_PROJNAME}_bot:${APP_VERSION}
    networks:
      - db-tunnel
    expose:
    - 5000
    ports:
    - 8000:5000
    depends_on:
      - db
    links:
    - db:newbie_db
networks:
  db-tunnel:
volumes:
  database_data:
    driver: local
